### ISSUE TITLE
Fix Time for some Feeds

### ISSUE THREAD

**Issue by TheOneImprove** [jocmp/capyreader#353] opened 2024-09-11 13:41 UTC
### Steps to Reproduce

1.Fetch the feed entries.

What is currently happening: all or some of them fetch as delivered at the current time and date.

Example Feeds:
Have I been Pwned: https://feeds.feedburner.com/HaveIBeenPwnedLatestBreaches

Almodon (Arabic): https://www.almodon.com/rss

## To do

- [ ] https://eurasianet.org/rss matches `Sep 23, 2024`
- [ ] https://www.crisisgroup.org/rss
- [ ] https://knowablemagazine.org/rss

**Comment by jocmp** [comment] 2024-09-12 02:15
hey @TheOneImprove - thanks for the links. both of these sites are using non-standard timestamp formats. in those cases the app falls back to the "arrived at" time for each article. I'll add some code to handle these cases.

**Comment by jocmp** [comment] 2024-09-13 21:40
@TheOneImprove - I have a fix up for the [first feed](https://feeds.feedburner.com/HaveIBeenPwnedLatestBreaches) that I'll include in the next version. Here's a demo of what that looks like:

<img src="https://github.com/user-attachments/assets/241d7000-324e-4bd1-b711-fafaff3cca5f" width="400px">

I'm not sure I have a good fix for the other feed. That one posts published dates with future timestamps like this article: https://www.almodon.com/politics/2024/9/14/إسرائيل-تجمع-الميدانين-اللبناني-والسوري-إنزالات-الكومندوس-البداية. So the issue for that feed is not a parsing bug.

**Comment by jocmp** [comment] 2024-09-15 18:54
That sounds good to me. I'll add handling for future timestamps with #361. Thanks for the kind words!

**Comment by jocmp** [comment] 2024-09-16 19:35
@TheOneImprove which version number are you seeing on F-Droid? F-Droid's builds usually have a lag up to a week and the fix is available in [2024.09.1049](https://github.com/jocmp/capyreader/releases/tag/2024.09.1049) which I created yesterday.

The [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/com.capyreader.app) version is usually available more quickly if you want to [add an F-Droid repo](https://f-droid.org/tutorials/add-repo/). I would expect that to update to 2024.09.1049 in a day or two.

**Comment by jocmp** [comment] 2024-09-16 22:12
I'm not seeing the issue anymore on 2024.09.1049. Let me know how it compares to what you're seeing. Here's what I have.

Times are correct for https://feeds.feedburner.com/HaveIBeenPwnedLatestBreaches

<img src="https://github.com/user-attachments/assets/1847f8c7-1da4-4725-925e-ca2ef9c89b35" width="300px"> 

For https://www.almodon.com/rss future times are saved as the "arrived at" time. This is how Feedbin handles future times and it ensures that there's a specific point-in-time to avoid showing "Just now" or a future date. The problem with future dates is that they may never arrive depending on what the server sends back.

Note how the published date is 5:04PM while the current time is 5:06PM. This is different to how it was previously where the published date was always kept in the future.

<img src="https://github.com/user-attachments/assets/60ef0c5b-bfd2-421b-998b-d64c6cdaa27a" width="300px">

**Comment by jocmp** [comment] 2024-10-03 02:12
A small update

- eurasianet.org/rss is fixed with https://github.com/jocmp/capyreader/pull/407. I'll include that in the next release
- https://knowablemagazine.org/rss formats correctly in browsers but has inconsistent behavior that I'm not able to fix
- I'm planning on adding support for https://www.crisisgroup.org/rss still. They change the formatting based on the article language so I need to find the correct formatting rules.

Thanks for your patience!

**Comment by narinishi** [comment] 2024-12-22 07:17
Hi, Capy Reader is showing all posts from the following feed as being on the current date https://www.the-digital-picture.com/News-RSS.aspx
They are specified as such `<pubDate>Sun, 22 Dec 2024 00:00:00 EDT</pubDate>`, which is following standards as far as I'm aware.

**Comment by jocmp** [comment] 2024-12-22 18:32
@narinishi yep! that's a standard format. i'm not seeing a problem with that feed in my testing for that feed. 

<img src="https://github.com/user-attachments/assets/c6983a8a-02f2-41a7-8436-8c14a530d203" width="300px" />

**Comment by narinishi** [comment] 2024-12-23 10:50
> @narinishi yep! that's a standard format. i'm not seeing a problem with that feed in my testing.
> 
> <img alt="" width="300px" src="https://private-user-images.githubusercontent.com/9521010/398005220-c6983a8a-02f2-41a7-8436-8c14a530d203.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NTA3NjYsIm5iZiI6MTczNDk1MDQ2NiwicGF0aCI6Ii85NTIxMDEwLzM5ODAwNTIyMC1jNjk4M2E4YS0wMmYyLTQxYTctODQzNi04YzE0YTUzMGQyMDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjNUMTA0MTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGJmZmJhY2NjMjc0MGNiMWVhMzg3YzU5NzcxZGY5ZDU4Njk5ZTY2MzI3ODI3NTY3NTdkZmU0MjE0YTBjZDk4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rgbQFEXnuCB1aVagnfwEyqLQCCYrAdCJafg2Yx9SByw">

The specific URL I'm using is actually https://www.the-digital-picture.com/News-RSS.aspx?Cat=Camera-Gear-Review-News
The article which appears first for me is `Just Posted: Sony FE 16-25mm F2.8 G Lens Review`, which has `<pubDate>Wed, 12 Jun 2024 09:00:00 EDT</pubDate>`
and `First Looks at Sony FE 28-70mm F2 GM Lens Image Quality` is right at the end, despite it being the most recent article

All of the posts from The Digital Picture show as being 1 day ago in Capy Reader, which is when I added the feed.

**Comment by jocmp** [comment] 2024-12-23 15:49
I'm still not able to replicate this with that category feed. Here's what I was able to see below - the "Just Posted..." is at the bottom of the feed. The "First Looks at..." article appears at the top.

Can you try unsubscribing and re-adding the feed? That would at least confirm whether this was a one-time bug or something persistent.

<table>
<tr>
</th>
</tr>
<tr>
<td valign="top">
<img src="https://github.com/user-attachments/assets/c4ab1bdd-d00a-4963-9dd3-4f41e4cf0f7f" width="300px">
</td>
<td valign="top">
<img src="https://github.com/user-attachments/assets/42502135-3321-4236-a728-936e7d816aff" width="300px">
</td>
</tr>
</table>

**Comment by narinishi** [comment] 2024-12-23 19:48
Still encountering the issue after re-adding.

![Screenshot_20241224-064417](https://github.com/user-attachments/assets/d181b3e8-b1bc-4614-a91b-1eec32b55e76)

**Comment by jocmp** [comment] 2024-12-23 20:09
@narinishi thanks for the screenshot. I noticed the time says 06:44. I should have asked sooner - can you confirm what language/timezone you're using? I think this might be a parser issue that assumes en-US. 

I was able to replicate your issue by changing my locale to en-AU. If that's the root cause I have a fix that I'll push for the next release.

**Comment by narinishi** [comment] 2024-12-23 20:47
> @narinishi thanks for the screenshot. I noticed the time says 06:44. I should have asked sooner - can you confirm what language/timezone you're using? I think this might be a parser issue that assumes en-US.
> 
> I was able to replicate your issue by changing my locale to en-AU. If that's the root cause I have a fix that I'll push for the next release.

Ah yep, I do have it set to Australia. 24-hour time isn't the default though, I manually set that.

**Closed** 2024-12-31 21:18 UTC
Labels: bug
