### ISSUE TITLE
Can't add Arabic UN News RSS feed 

### ISSUE THREAD

**Issue by TheOneImprove** [jocmp/capyreader#358] opened 2024-09-15 09:13 UTC
### Steps to Reproduce

1. Add the arabic UN news feed.

What is happening: the client show that there is no rss feed at the url.

Url:
https://news.un.org/feed/subscribe/ar/news/all/rss.xml

### Expected behavior

The client fetch the RSS feed.

### Device, Operating system, and app version

Android 14.

**Comment by jocmp** [comment] 2024-09-15 18:59
@TheOneImprove I'm not able to reproduce this. I was able to add https://news.un.org/feed/subscribe/ar/news/all/rss.xml and this is what I see. Can you try again and see if it's working now? If not I'll take a closer look.

![Screenshot_20240915_135740](https://github.com/user-attachments/assets/4b398718-4d12-4ace-9dc4-42774941b09e)

**Comment by jocmp** [comment] 2024-09-16 14:17
Sorry, I don't have a fix for this yet. I'm able to add the feed myself on 2024.09.1046, so I need to add the ability to export logs in order to diagnose this. I'll carve out some time to work on that soon.

**Closed** 2024-12-31 21:19 UTC
Labels: bug
